#ifndef ACADSUPFILES_GLOBAL_H
#define ACADSUPFILES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACADSUPFILES_LIBRARY)
#  define ACADSUPFILESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACADSUPFILESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACADSUPFILES_GLOBAL_H
