#ifndef WORKBYDATEUSER_GLOBAL_H
#define WORKBYDATEUSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WORKBYDATEUSER_LIBRARY)
#  define WORKBYDATEUSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WORKBYDATEUSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WORKBYDATEUSER_GLOBAL_H
