#ifndef SAVELOADLIB_GLOBAL_H
#define SAVELOADLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAVELOADLIB_LIBRARY)
#  define SAVELOADLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAVELOADLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAVELOADLIB_GLOBAL_H
